# Generated by Django 3.0.2 on 2021-03-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='settings',
            field=models.TextField(blank=True, null=True, verbose_name='settings for app'),
        ),
    ]
