# Generated by Django 3.1 on 2020-08-08 03:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='部位名称')),
                ('incidence', models.IntegerField(choices=[(0, '低'), (1, '中'), (2, '高')], verbose_name='发病率')),
                ('parent', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='pid', to='medicaly.bodypart', verbose_name='父级部位')),
            ],
            options={
                'verbose_name': '身体部位',
                'verbose_name_plural': '身体部位',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='疾病名称')),
                ('incidence', models.IntegerField(choices=[(0, '低'), (1, '中'), (2, '高')], verbose_name='发病率')),
            ],
            options={
                'verbose_name': '疾病',
                'verbose_name_plural': '疾病',
            },
        ),
        migrations.CreateModel(
            name='OrganSystem',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='身体系统')),
            ],
            options={
                'verbose_name': '身体系统',
                'verbose_name_plural': '身体系统',
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='症状名称')),
                ('accuracy', models.IntegerField(choices=[(0, '无法理解'), (1, '部分理解'), (2, '十分显著')], verbose_name='明显程度')),
                ('body_part', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='symptoms', to='medicaly.bodypart')),
                ('organ_system', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='symptoms', to='medicaly.organsystem')),
            ],
            options={
                'verbose_name': '症状',
                'verbose_name_plural': '症状',
            },
        ),
        migrations.CreateModel(
            name='SymptomToDisease',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('relevence', models.IntegerField(choices=[(0, '次要'), (1, '重要'), (2, '必要')], verbose_name='关联程度')),
                ('disease', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dieases', to='medicaly.disease', verbose_name='疾病')),
                ('symptom', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='symptoms', to='medicaly.symptom', verbose_name='症状')),
            ],
            options={
                'verbose_name': '疾病-症状 标注',
                'verbose_name_plural': '疾病-症状 标注',
            },
        ),
    ]
